### ISSUE TITLE
請問下載完 ipa 檔後的事項

### ISSUE THREAD

**Issue by YueJun1991** [JeziL/IPASearch#1]
下載成功之後，改後綴為 zip 之後：
class-dump -H /Payload 路徑的 App -o /target/路徑
但是依舊是經過加密的。而我看了一下 Clutch 似乎一定要運行在越獄的設備上？
這裡不是很懂，感謝指教。

**Comment by JeziL** [comment]
试试 ：
```otool -l <executable_file> | grep -A5 LC_ENCRYP```

看 `cryptid` 字段的值，为 1 就是经过加密，为 0 已经解密。如果确实为 1 那就是 PP 资源的问题，Clutch 之类的工具肯定要跑在越狱设备上的。

**Comment by YueJun1991** [comment]
@JeziL 經測試，發現這個值確實為1 ，看來沒有機會在不越獄的情況下拿到 .h 檔了嗎

**Comment by JeziL** [comment]
没有越狱设备的话就只能到各家盗版助手们那里下载 ipa 试试了

**Comment by YueJun1991** [comment]
感謝回復。測試幾個 App 之後，有的有加密有的沒加密得看運氣~感謝，可以 close 啦
